Update get_expression_data.py fixed numpy error
Changed line 34 from "np.float" to "float" to solve:
Traceback (most recent call last):
  File "/software/Searchlight2-master/software/Searchlight2.py", line 92, in <module>
    workflows(global_variables)
  File "/software/Searchlight2-master/software/workflows/workflows.py", line 23, in workflows
    mde_workflow(global_variables)
  File "/software/Searchlight2-master/software/workflows/mde/mde_workflow.py", line 13, in mde_workflow
    run_mde_workflow(global_variables, "all_genes")
  File "/software/Searchlight2-master/software/workflows/mde/run_mde_workflows.py", line 91, in run_mde_workflow
    mde_dict = differential_expression_signature_helper(global_variables, out_path, de_IDs, mde_dict)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/Searchlight2-master/software/workflows/mde/statistical_analysis_helpers/differential_expression_signature_helper.py", line 10, i>
    mde_dict = differential_expression_signature(global_variables, signature_candidate_list_path, differential_expression_signature_out_path, de_I>
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^>
  File "/software/Searchlight2-master/software/statistical_analysis_tools/differential_expression_signature/differential_expression_signature.py",>
    genes_by_signature = get_expression_data(data,sample_list,genes_by_signature,signatures_by_gene)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/Searchlight2-master/software/statistical_analysis_tools/differential_expression_signature/get_expression_data.py", line 34, in g>
    zscore_data = np.array(expression_data).astype(np.float)
                                                   ^^^^^^^^
  File "/software/anaconda3/lib/python3.11/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify>
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?